apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    app: backend-app   # Corrected selector label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
